Article Title: Warming resistant corals from the Gulf of Aqaba live close to their cold-water bleaching threshold
Article Authors: Jessica Bellworthy, Maoz Fine

Code written by Jessica Bellworthy


Load libraries, data, and view
```{r}
# load packages
library(ggplot2)
library(ggsci)
library(cowplot)

rd_a <- read.csv("acropora_rawdata_clean.csv")
str(rd_a)
View(rd_a)
colnames(rd_a)

# x axis label names
mynames <- c("WINTER", "SUMMER")
```


####### Algal parameters #########

```{r}
# cellscm plot
a_cellcm <- ggplot(rd_a, aes(day, cellcm, fill = treatment))+
geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2, key_glyph = rectangle_key_glyph(fill = fill, colour = "black", padding = margin(2, 2, 2, 2)))+
  geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(title = element_text(face = "bold"), axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
  scale_fill_simpsons(labels = c("T0", "T-1", "T-3"))+
  scale_y_continuous(limits = c(-0.8, 8), breaks = seq(0,8,2))+
  labs(x="", y=expression(cells  ~'×'~10^{5} ~cm^{-2} ))+
  guides(shape = FALSE, fill = FALSE) +
  annotate("text", x = c(1.75, 2, 2.25), y = c(-0.6,-0.6,-0.6), label = c("a", "a", "b"), size = 2)
  
a_cellcm
```

```{r}
# net photosynthesis cm plot
a_pscm <- ggplot(rd_a, aes(day, pscm, fill = treatment))+
geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
  scale_fill_simpsons()+
  scale_y_continuous(limits = c(-0.05, 0.15), breaks = seq(-0.05,0.15, 0.05))+
  labs(x="", y=expression(~µmol ~O[2] ~h^{-1} ~cm^{-2}))+
  guides(shape = FALSE, fill = FALSE)+
  annotate("text", x = c(0.75, 1, 1.25), y = c(-0.04,-0.04,-0.04), label = c("a", "b", "b"), size = 2)

a_pscm
```


```{r}
# chlcm plot
a_chlcm <- ggplot(rd_a, aes(day,chlcm, fill = treatment))+
geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
 scale_fill_simpsons()+
  scale_y_continuous(limits = c(-5, 55), breaks = seq(0,60,10))+
 labs(x="", y=expression(~µg ~chl ~cm^{-2}))+
   guides(shape = FALSE, fill = FALSE)

a_chlcm
```


####### Coral parameters #########

```{r}
# remove one outlier from t2m6, row 14
rcm_rd_a =  rd_a[-c(14), ]

# respiration cm plot
a_rcm <- ggplot(rcm_rd_a, aes(day, rcm, fill = treatment))+
 geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
  scale_fill_simpsons()+
  scale_y_continuous(limits = c(0, 0.15), breaks = seq(0, 0.15, 0.05))+
 labs(x="", y=expression(~µmol ~O[2] ~h^{-1} ~cm^{-2}))+
  guides(shape = FALSE, fill = FALSE)

a_rcm
```


```{r}
# total protein cm plot
a_tpcm <- ggplot(rd_a, aes(day, tpcm, fill = treatment))+
 geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
  scale_fill_simpsons()+
  scale_y_continuous(limits = c(0, 1), breaks = seq(0,1,0.2))+
  labs(x="", y=expression(~mg ~protein^{-1} ~cm^{-2}))+
  guides(shape = FALSE, fill = FALSE)

a_tpcm
```


####### Photochemistry #########
```{r}
# fvfm plot
a_fvfm <- ggplot(rd_a, aes(day, fvfm, fill = treatment))+
geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
 scale_fill_simpsons()+
  scale_y_continuous(limits = c(0.2, 0.61), breaks = seq(0.2,0.6,0.2))+
 labs(x="", y=expression(~F[V]/F[M]))+
   guides(shape = FALSE, fill = FALSE)+
  annotate("text", x = c(0.75, 1, 1.25), y = c(0.22,0.22, 0.22), label = c("a", "b", "b"), size = 2)

a_fvfm
```


```{r}
# remove the one anomaly from t2min6, row 13
etr_rd_a =  rd_a[-c(13), ]

# etr plot
a_etr <- ggplot(etr_rd_a, aes(day, etr, fill = treatment))+
geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
 scale_fill_simpsons()+
  scale_y_continuous(limits = c(-5, 80), breaks = seq(0,80,20))+
 labs(x="", y=expression(~rETR[max]))+
   guides(shape = FALSE, fill = FALSE)+
  annotate("text", x = c(0.75, 1, 1.25, 1.75, 2, 2.25), y = c(-3,-3,-3,-3,-3,-3), label = c("a", "a", "b", "a", "a", "b"), size = 2)

a_etr
```


```{r}
# ik plot
a_ik <- ggplot(rd_a, aes(day, ik, fill = treatment))+
geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
 scale_fill_simpsons()+
  scale_y_continuous(limits = c(-10, 190), breaks = seq(0,190,30))+
 labs(x="", y=expression(~I[K]))+
   guides(shape = FALSE, fill = FALSE)+
  annotate("text", x = c(0.75, 1, 1.25), y = c(-5,-5,-5), label = c("a", "a", "b"), size = 2)

a_ik
```


```{r}
# alpha plot
a_alpha <- ggplot(rd_a, aes(day, alpha, fill = treatment))+
geom_boxplot(outlier.shape = "", fatten = 0.5, alpha = 0.7, lwd = 0.2)+
geom_point(position = position_dodge(width = 0.75), aes(group=treatment, shape=geno), size = 0.75)+
  scale_x_discrete(labels = mynames)+
 theme_classic()+
  theme(axis.text.x =element_text(size = 8, colour = "black"), axis.text.y =element_text(size = 8, colour = "black"), axis.title.y = element_text(size = 8, colour = "black"), legend.position = c(0.85, 0.9), legend.title = element_blank(), legend.key.size = unit(6, "mm"))+
 scale_fill_simpsons()+
  scale_y_continuous(limits = c(0.25, 0.92), breaks = seq(0.3,0.9,0.2))+
 labs(x="", y=expression(alpha))+
   guides(shape = FALSE, fill = FALSE)+
  annotate("text", x = c(0.75, 1, 1.25), y = c(0.27,0.27,0.27), label = c("a", "a", "b"), size = 2)

a_alpha
```
